/*
 * File: app/view/dadespacient.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RegCr.view.dadespacient', {
    extend: 'Ext.navigation.View',
    alias: 'widget.DadesPacient',

    config: {
        itemId: 'dadespacient',
        ui: 'light',
        items: [
            {
                xtype: 'fieldset',
                instructions: 'el codi',
                title: 'Dades',
                items: [
                    {
                        xtype: 'numberfield',
                        label: 'Codi',
                        name: 'Codi'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'Nom',
                        label: 'Nom'
                    },
                    {
                        xtype: 'emailfield',
                        label: 'Correu',
                        placeHolder: 'email@exemple.com'
                    },
                    {
                        xtype: 'togglefield',
                        itemId: 'PressioTgl',
                        label: 'Pressi&oacute;',
                        value: 1
                    },
                    {
                        xtype: 'togglefield',
                        itemId: 'GlucosaTgl',
                        label: 'Glucosa',
                        value: 1
                    },
                    {
                        xtype: 'button',
                        itemId: 'dadesbutton',
                        ui: 'confirm-round',
                        text: 'Desar'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onDadesbuttonTap',
                event: 'tap',
                delegate: '#dadesbutton'
            }
        ]
    },

    onDadesbuttonTap: function(button, e, options) {

    }

});