/*
 * File: app/view/GraficPrs.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RegCr.view.GraficPrs', {
    xtype: 'line',
    extend: 'Ext.chart.Chart',
    config: {
        title: 'Hist&ograve;ric de Pressi&oacute;',
        iconCls: 'line',
        cls: 'chartpanel',
        interactions: ['reset', {
            type: 'panzoom'
        }, {
            type: 'iteminfo',
            gesture: 'tap',
            listeners: {
                show: function (interaction, item, panel) {
				  var record = item.storeItem;
				  panel.setHtml(
					'<b>' + record.get('Data').toDateString() + ':</b>' +
					'<ul>' +
					  '<li>Min: ' + record.get('minima') + '</li>' +
					  '<li>Max: ' + record.get('maxima') + '</li>' +
					  '<li>Pols: ' + record.get('pulsacions') + '</li>' +
					'</ul>'
				  );
                }
            }
        }],
        animate: true,
        store: 'StoreDadesP',
        axes: [
            {
                type: 'Numeric',
                position: 'left',
                minimum: 20,
                label: {
                    renderer: RegCr.commify
                },
                adjustMinimumByMajorUnit: 0,
                fields: ['maxima','minima','pulsacions'],
				roundToDecimal: true,
                decimals: 0,
                title: 'Nivell Pressió',
                grid: {
                    odd: {
                        stroke: '#555'
                    },
                    even: {
                        stroke: '#777'
                    }
                }
            },
            {
                type: 'Time',
                position: 'bottom',
                fields: ['Data'],
                title: 'Data',
				dateFormat: ' d M Y',
                label: {
                    rotate: {
                        degrees: 45
                    }
                }
            }
        ],
        legend: {
            position: Ext.os.is.Phone ? 'left' : 'top'
        },
        theme: 'Energy',
        series: [
            {
                type: 'line',
                highlight: false,
                showMarkers: false,
                fill: true,
                smooth: true,
                axis: 'left',
                xField: 'Data',
                yField: 'minima',
                title: ['minima']
            },
			{
                type: 'line',
                highlight: false,
                showMarkers: false,
                fill: true,
                smooth: true,
                axis: 'left',
                xField: 'Data',
                yField: 'maxima',
                title: ['maxima']
            },
						{
                type: 'line',
                highlight: false,
                showMarkers: false,
                fill: false,
                smooth: true,
                axis: 'left',
                xField: 'Data',
                yField: 'pulsacions',
                title: ['pulsacions']
            }
        ],
        listeners: {
            afterrender: function (me) {
                me.on('beforerefresh', function () {
                    if (me.ownerCt.getActiveItem().id !== me.id) {
                        return false;
                    }
                }, me);
            }
        }
    }
});