/*
 * File: app/view/GraficGlc.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define("RegCr.view.GraficGlc", {
    xtype: 'line',
    extend: 'Ext.chart.Chart',
    config: {
        title: 'Hist&ograve;ric de Glucosa',
        iconCls: 'line',
        cls: 'chartpanel',
        interactions: ['reset', {
            type: 'panzoom'
        }, {
            type: 'iteminfo',
            gesture: 'tap',
            listeners: {
                show: function (interaction, item, panel) {
					var record = item.storeItem;
					panel.setHtml(
						'<b>' + record.get('Data').toDateString() + ':</b>' +
						'<ul>' +
							'<li>Glucosa: ' + record.get('Glucosa') + '</li>' +
						'</ul>'
					);
				}
			}
        }],
        animate: true,
        store: 'StoreDadesG',
        axes: [
            {
                type: 'Numeric',
                position: 'left',
                minimum: 20,
                label: {
                    renderer: RegCr.commify
                },
                adjustMinimumByMajorUnit: 0,
                fields: ['Glucosa'],
				roundToDecimal: true,
                decimals: 0,
                title: 'Nivell Glucosa',
                grid: {
                    odd: {
                        stroke: '#777'
                    },
                    even: {
                        stroke: '#555'
                    }
                }
            },
            {
                type: 'Time',
                position: 'bottom',
                fields: ['Data'],
                title: 'Data',
				dateFormat: ' d M Y',
                label: {
                    rotate: {
                        degrees: 45
                    }
                }
            }
        ],
        legend: {
            position: Ext.os.is.Phone ? 'left' : 'top'
        },
        theme: 'Energy',
        series: [
            {
                type: 'line',
                highlight: false,
                showMarkers: false,
                fill: true,
                smooth: true,
                axis: 'left',
                xField: 'Data',
                yField: 'Glucosa',
                title: ['Glucosa']
            }
        ],
        listeners: {
            afterrender: function (me) {
                me.on('beforerefresh', function () {
                    if (me.ownerCt.getActiveItem().id !== me.id) {
                        return false;
                    }
                }, me);
            }
        }
    }
});