/*
 * File: app/view/HistGlucosa.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RegCr.view.HistGlucosa', {
    extend: 'Ext.tab.Panel',

    config: {
        id: 'HistGluc',
        ui: 'light',
        items: [
            {
                xtype: 'list',
                id: 'LisGluc',
                itemTpl: [
                    '<div>{Data:date("d/m/Y")} - Sucre: {Glucosa}</div>'
                ],
                store: 'StoreDadesG',
                grouped: false,
                title: 'Llista'
            }
        ]
    }

});