/*
 * File: app/view/PanelPrincipal.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PanelPrincipal', {
    extend: 'Ext.navigation.View',
    alias: 'widget.PanPrinc',

    config: {
        ui: 'light',
        defaultBackButtonText: '\'Enrere\'',
        items: [
            {
                xtype: 'nestedlist',
                height: 300,
                itemId: 'mynestedlist',
                store: 'MenuList',
                title: 'Opcions',
                activeItem: 1,
                toolbar: {
                    xtype: 'toolbar',
                    height: 40
                }
            }
        ],
        navigationBar: {
            height: 40
        },
        listeners: [
            {
                fn: 'onMynestedlistLeafItemTap',
                event: 'leafitemtap',
                delegate: '#mynestedlist'
            }
        ]
    },

    onMynestedlistLeafItemTap: function(nestedlist, list, index, target, record, e, options) {


        if (record.get('text')=='Detalls'){
            var tabPanel = Ext.create('Ext.Panel', {
                title: 'Registre cr&ograve;nics',
                styleHtmlContent:true,
                items: [
                {
                    html: '<br>Registre de dades de pacients cr&ograve;nics<br>Versi&oacute; 1.0'
                }
                ]
            });
            this.push(tabPanel);
        }

    }

});